name: 🚀 Deploy Django API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            APP=/home/ramozobu/api
            VENV=/home/ramozobu/virtualenv/api/3.10/bin/activate
            LOG=/home/ramozobu/deploy.log

            {
              echo "===== DEPLOY START $(date) ====="
              echo "PYTHON:" $(which python)
              echo "PIP:" $(which pip)
              pip list
              cd $APP

              git fetch origin
              git reset --hard origin/main

              source $VENV

              pip uninstall mysqlclient -y || true
              pip uninstall MySQL-python -y || true
              pip install --no-cache-dir -r requirements.txt

              python manage.py migrate --noinput
              python manage.py collectstatic --noinput
              python manage.py check --deploy

              touch tmp/restart.txt

              echo "===== DEPLOY DONE $(date) ====="
            } >> $LOG 2>&1
